# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres?characterEncoding=UTF-8
    username: postgres
    password: V0ldm0tbr0
    platform: postgres

  # ===============================
  # = Resource configurations
  # ===============================
  resources:
    static-locations: classpath:/static/

  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # ===============================
  # = MAIL configurations
  # ===============================
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: acgy1029@gmail.com
    password: p@55W0rds
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

# ===============================
# = Logging configurations
# ===============================
#logging:
#  level:
#    root: WARN
#    com.memorynotfound: DEBUG
#    org.springframework.web: INFO
#    org.springframework.security: INFO